CREATE TABLE tb_feira (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    LONG VARCHAR(255),
    LAT VARCHAR(255),
    SETCENS VARCHAR(255),
    AREAP VARCHAR(255),
    CODDIST VARCHAR(255),
    DISTRITO VARCHAR(255),
    CODSUBPREF VARCHAR(50),
    SUBPREFE VARCHAR(255),
    REGIAO5 VARCHAR(100),
    REGIAO8 VARCHAR(100),
    NOME_FEIRA VARCHAR(255),
    REGISTRO VARCHAR(100),
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(100),
    BAIRRO VARCHAR(100),
    REFERENCIA VARCHAR(255)
) AS SELECT * FROM CSVREAD('classpath:/DEINFO_AB_FEIRASLIVRES_2014.csv');